/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Falcon.Calculator;
//import Falcon.Conrollers.Calculations;

import Falcon.Integration.InteDiff;
import Falcon.Graph.G_Calc;
import java.awt.Desktop;
import java.io.IOException;

/**
 *
 * @author Falcon -> achintha,Pubudu,Nethmi,Rajitha,Mano(Team Falcon)
 */



public class Calculator extends javax.swing.JFrame {

    Calculations calculations =new Calculations();
//    InteDiff intediff=new InteDiff();
    String formula= "";
    
    String EquationsHistory[]= new String[100];
    
    int current_h_pos= 0;
    
    char mode= 'd';
    
    String answer= "0.0";
    
    int current_cur_pos= 0;
    
    double mem= 0.0;
    double mem_x=0.0; 
    double mem_y=0.0;
    double mem_z=0.0;
    
    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
        for(int i=0; i<EquationsHistory.length; i++) {
			EquationsHistory[i]= "";
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonX = new javax.swing.JButton();
        jButtonIntegration = new javax.swing.JButton();
        jButtonUnitConverter = new javax.swing.JButton();
        jButtonPower = new javax.swing.JButton();
        jButtonMultiply = new javax.swing.JButton();
        jButtonCos = new javax.swing.JButton();
        jButtonSquareRoot = new javax.swing.JButton();
        jButtonPower2 = new javax.swing.JButton();
        jButtonPower3 = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonSimpleCalculator = new javax.swing.JButton();
        jButtonLog = new javax.swing.JButton();
        jButtonAdvanceCalculator = new javax.swing.JButton();
        jButtonRandom = new javax.swing.JButton();
        jButtonNull4 = new javax.swing.JButton();
        jButtonPi = new javax.swing.JButton();
        jButtonRightBracket = new javax.swing.JButton();
        jTexOutputDisplay = new javax.swing.JTextField();
        jButtonSin = new javax.swing.JButton();
        jButtonNull3 = new javax.swing.JButton();
        jButtonDivide = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jTextInputDisplay = new javax.swing.JTextField();
        jButtonLeftBracket = new javax.swing.JButton();
        jButtonTan = new javax.swing.JButton();
        jButtonAllClear = new javax.swing.JButton();
        jButtonUCDLogo = new javax.swing.JButton();
        jButtonLn = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonEqual = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButtonGraph = new javax.swing.JButton();
        jToggleStore = new javax.swing.JToggleButton();
        jButtonNull8 = new javax.swing.JButton();
        jButtonNull9 = new javax.swing.JButton();
        jButtonNull10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WiCaDi ");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonX.setBackground(new java.awt.Color(255, 153, 51));
        jButtonX.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonX.setForeground(new java.awt.Color(255, 255, 255));
        jButtonX.setText("X");
        jButtonX.setToolTipText("x variable button");
        jButtonX.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 94, 72));

        jButtonIntegration.setBackground(new java.awt.Color(255, 153, 51));
        jButtonIntegration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonIntegration.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIntegration.setText("Integration/Differentiation");
        jButtonIntegration.setToolTipText("Integration and differentiation button");
        jButtonIntegration.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonIntegration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntegrationActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonIntegration, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 362, 72));

        jButtonUnitConverter.setBackground(new java.awt.Color(255, 153, 51));
        jButtonUnitConverter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonUnitConverter.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUnitConverter.setText("Unit Converter");
        jButtonUnitConverter.setToolTipText("Graph Calculator");
        jButtonUnitConverter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonUnitConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnitConverterActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUnitConverter, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 180, 30));

        jButtonPower.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPower.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPower.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPower.setText("^");
        jButtonPower.setToolTipText("to the power button");
        jButtonPower.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPowerActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPower, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 94, 72));

        jButtonMultiply.setBackground(new java.awt.Color(255, 153, 51));
        jButtonMultiply.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMultiply.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultiply.setText("*");
        jButtonMultiply.setToolTipText("Multiply button");
        jButtonMultiply.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplyActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMultiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 94, 72));

        jButtonCos.setBackground(new java.awt.Color(255, 153, 51));
        jButtonCos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCos.setText("Cos");
        jButtonCos.setToolTipText("Trignometry cos button");
        jButtonCos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCos, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 94, 72));

        jButtonSquareRoot.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSquareRoot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSquareRoot.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSquareRoot.setText("√");
        jButtonSquareRoot.setToolTipText("Square Root Button");
        jButtonSquareRoot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSquareRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSquareRootActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSquareRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 94, 72));

        jButtonPower2.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPower2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPower2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPower2.setText("x²");
        jButtonPower2.setToolTipText("to the pwer 2 button");
        jButtonPower2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonPower2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPower2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPower2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 94, 72));

        jButtonPower3.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPower3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPower3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPower3.setText("x³");
        jButtonPower3.setToolTipText("to the power 3 button");
        jButtonPower3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonPower3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPower3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPower3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 94, 72));

        jButtonDelete.setBackground(new java.awt.Color(255, 153, 51));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("<-");
        jButtonDelete.setToolTipText("Delete Button");
        jButtonDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 94, 72));

        jButtonSimpleCalculator.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSimpleCalculator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSimpleCalculator.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSimpleCalculator.setText("Simple");
        jButtonSimpleCalculator.setToolTipText("Simple Calculator");
        jButtonSimpleCalculator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSimpleCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpleCalculatorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSimpleCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 30));

        jButtonLog.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLog.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLog.setText("Log");
        jButtonLog.setToolTipText("Logarithimic button");
        jButtonLog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 94, 72));

        jButtonAdvanceCalculator.setBackground(new java.awt.Color(255, 153, 51));
        jButtonAdvanceCalculator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonAdvanceCalculator.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdvanceCalculator.setText("Scientific");
        jButtonAdvanceCalculator.setToolTipText("Advance Calculator");
        jButtonAdvanceCalculator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonAdvanceCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdvanceCalculatorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdvanceCalculator, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 180, 30));

        jButtonRandom.setBackground(new java.awt.Color(255, 153, 51));
        jButtonRandom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRandom.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRandom.setText("Random");
        jButtonRandom.setToolTipText("Random value generator button");
        jButtonRandom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRandom, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 94, 72));

        jButtonNull4.setBackground(new java.awt.Color(255, 153, 51));
        jButtonNull4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonNull4.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNull4.setToolTipText("Null Button");
        jButtonNull4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonNull4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNull4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNull4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 94, 72));

        jButtonPi.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPi.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPi.setText("π");
        jButtonPi.setToolTipText("π value button");
        jButtonPi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPi, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 94, 72));

        jButtonRightBracket.setBackground(new java.awt.Color(255, 153, 51));
        jButtonRightBracket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonRightBracket.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRightBracket.setText(")");
        jButtonRightBracket.setToolTipText("Right Bracket");
        jButtonRightBracket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonRightBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRightBracketActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRightBracket, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 94, 72));

        jTexOutputDisplay.setBackground(new java.awt.Color(0, 0, 0));
        jTexOutputDisplay.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTexOutputDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jTexOutputDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTexOutputDisplay.setText("Answer");
        jTexOutputDisplay.setToolTipText("Output Display");
        jTexOutputDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexOutputDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(jTexOutputDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 814, 80));

        jButtonSin.setBackground(new java.awt.Color(255, 153, 51));
        jButtonSin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSin.setText("Sin");
        jButtonSin.setToolTipText("Trignometry sin button");
        jButtonSin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSinActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 94, 72));

        jButtonNull3.setBackground(new java.awt.Color(255, 153, 51));
        jButtonNull3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonNull3.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNull3.setText("M");
        jButtonNull3.setToolTipText("Memmory button");
        jButtonNull3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonNull3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNull3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNull3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 94, 72));

        jButtonDivide.setBackground(new java.awt.Color(255, 153, 51));
        jButtonDivide.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDivide.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDivide.setText("÷");
        jButtonDivide.setToolTipText("Divide Button");
        jButtonDivide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivideActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDivide, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 94, 72));

        jButtonPlus.setBackground(new java.awt.Color(255, 153, 51));
        jButtonPlus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPlus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPlus.setText("+");
        jButtonPlus.setToolTipText("Plus button");
        jButtonPlus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 94, 72));

        jButtonMinus.setBackground(new java.awt.Color(255, 153, 51));
        jButtonMinus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonMinus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMinus.setText("-");
        jButtonMinus.setToolTipText("Minus button");
        jButtonMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 94, 72));

        jTextInputDisplay.setBackground(new java.awt.Color(0, 0, 0));
        jTextInputDisplay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextInputDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jTextInputDisplay.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextInputDisplay.setText("Equation");
        jTextInputDisplay.setToolTipText("Input Display");
        jTextInputDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextInputDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(jTextInputDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 814, 80));

        jButtonLeftBracket.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLeftBracket.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLeftBracket.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLeftBracket.setText("(");
        jButtonLeftBracket.setToolTipText("Left Bracket");
        jButtonLeftBracket.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonLeftBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLeftBracketActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLeftBracket, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 94, 72));

        jButtonTan.setBackground(new java.awt.Color(255, 153, 51));
        jButtonTan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTan.setText("Tan");
        jButtonTan.setToolTipText("Trignometry Tan button");
        jButtonTan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTanActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 94, 72));

        jButtonAllClear.setBackground(new java.awt.Color(255, 153, 51));
        jButtonAllClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonAllClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAllClear.setText("AC");
        jButtonAllClear.setToolTipText("All Clear Button");
        jButtonAllClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAllClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAllClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 94, 72));

        jButtonUCDLogo.setBackground(new java.awt.Color(255, 153, 51));
        jButtonUCDLogo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonUCDLogo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUCDLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/help.png"))); // NOI18N
        jButtonUCDLogo.setToolTipText("Help");
        jButtonUCDLogo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonUCDLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUCDLogoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUCDLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 90, 30));

        jButtonLn.setBackground(new java.awt.Color(255, 153, 51));
        jButtonLn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonLn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLn.setText("ln");
        jButtonLn.setToolTipText("natural Ln button");
        jButtonLn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLnActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 94, 72));

        jButtonY.setBackground(new java.awt.Color(255, 153, 51));
        jButtonY.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonY.setForeground(new java.awt.Color(255, 255, 255));
        jButtonY.setText("Y");
        jButtonY.setToolTipText("y variable button");
        jButtonY.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonY, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 94, 72));

        jButtonZ.setBackground(new java.awt.Color(255, 153, 51));
        jButtonZ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonZ.setForeground(new java.awt.Color(255, 255, 255));
        jButtonZ.setText("Z");
        jButtonZ.setToolTipText("z variable button");
        jButtonZ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 94, 72));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("9");
        jButton9.setToolTipText("Number 9 button");
        jButton9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 94, 72));

        jButtonEqual.setBackground(new java.awt.Color(255, 153, 51));
        jButtonEqual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEqual.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEqual.setText("=");
        jButtonEqual.setToolTipText("equal sign button");
        jButtonEqual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 94, 72));

        jButtonDot.setBackground(new java.awt.Color(0, 0, 0));
        jButtonDot.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDot.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDot.setText(".");
        jButtonDot.setToolTipText("decimal point button");
        jButtonDot.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 94, 72));

        jButton0.setBackground(new java.awt.Color(0, 0, 0));
        jButton0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton0.setForeground(new java.awt.Color(255, 255, 255));
        jButton0.setText("0");
        jButton0.setToolTipText("Number 0 button");
        jButton0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 182, 72));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("1");
        jButton1.setToolTipText("Number 1 button");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 94, 72));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("2");
        jButton2.setToolTipText("Number 2 button");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 94, 72));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("3");
        jButton3.setToolTipText("Number 3 button");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 94, 72));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("4");
        jButton4.setToolTipText("Number 4 button");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 94, 72));

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("5");
        jButton5.setToolTipText("Number 5 button");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 94, 72));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("6");
        jButton6.setToolTipText("Number 6 button");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 94, 72));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("7");
        jButton7.setToolTipText("Number 7 button");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 94, 72));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("8");
        jButton8.setToolTipText("Number 8 button");
        jButton8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 94, 72));

        jButtonGraph.setBackground(new java.awt.Color(255, 153, 51));
        jButtonGraph.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonGraph.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGraph.setText("Graph");
        jButtonGraph.setToolTipText("Graph Calculator");
        jButtonGraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGraphActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 180, 30));

        jToggleStore.setBackground(new java.awt.Color(255, 153, 51));
        jToggleStore.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jToggleStore.setForeground(new java.awt.Color(255, 255, 255));
        jToggleStore.setText("Store");
        jToggleStore.setToolTipText("store toggle button to store x,y & z values");
        jToggleStore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jToggleStore.setBorderPainted(false);
        jToggleStore.setOpaque(true);
        jPanel1.add(jToggleStore, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 90, 72));

        jButtonNull8.setBackground(new java.awt.Color(255, 153, 51));
        jButtonNull8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonNull8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNull8.setText("M+");
        jButtonNull8.setToolTipText("Add to the memmory button");
        jButtonNull8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonNull8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNull8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNull8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 94, 72));

        jButtonNull9.setBackground(new java.awt.Color(255, 153, 51));
        jButtonNull9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonNull9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNull9.setText("M-");
        jButtonNull9.setToolTipText("Remove from the memmory button");
        jButtonNull9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonNull9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNull9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNull9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 320, 94, 72));

        jButtonNull10.setBackground(new java.awt.Color(255, 153, 51));
        jButtonNull10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonNull10.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNull10.setText("MC");
        jButtonNull10.setToolTipText("Memmory clear button");
        jButtonNull10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jButtonNull10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNull10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNull10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 94, 72));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void OutputDisplay() {
		jTextInputDisplay.setText(formula);
	}
    
    private void EquationHistory(String p) {
		for(int i=EquationsHistory.length-1; i>0; i--) {
			EquationsHistory[i]= EquationsHistory[i-1];
		}
		EquationsHistory[0]= p;
	}
    
    private String format_problem() {
		String tmp_problem= new String(formula);
		tmp_problem= tmp_problem.replace("Ans", answer+"");
		tmp_problem= tmp_problem.replace("M", mem+"");
		tmp_problem= tmp_problem.replace("X", mem_x+"");
		tmp_problem= tmp_problem.replace("Y", mem_y+"");
		tmp_problem= tmp_problem.replace("Z", mem_z+"");
		tmp_problem= tmp_problem.replace("π", "PI");
		return tmp_problem;
	}
    
    private void set_history(String p) {
		for(int i=EquationsHistory.length-1; i>0; i--) {
			EquationsHistory[i]= EquationsHistory[i-1];
		}
		EquationsHistory[0]= p;
	}
    
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //main window size and reszing function is disabled
        this.setResizable(false);
        this.setSize(362, 556);
        jTextInputDisplay.setSize(204, 49);
        
        
    }//GEN-LAST:event_formWindowActivated

    private void jButtonLeftBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLeftBracketActionPerformed
        // TODO add your handling code here:
        formula=formula+"(";
        OutputDisplay();
    }//GEN-LAST:event_jButtonLeftBracketActionPerformed

    private void jTextInputDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextInputDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextInputDisplayActionPerformed

    private void jButtonNull3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNull3ActionPerformed
        // TODO add your handling code here:
        formula= formula+ 'M';
	OutputDisplay();
        
    }//GEN-LAST:event_jButtonNull3ActionPerformed

    private void jButtonRightBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRightBracketActionPerformed
        // TODO add your handling code here:
        formula=formula+")";
        OutputDisplay();
    }//GEN-LAST:event_jButtonRightBracketActionPerformed

    private void jButtonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPiActionPerformed
        // TODO add your handling code here:
        
        formula = formula+"π";
	OutputDisplay();
        
    }//GEN-LAST:event_jButtonPiActionPerformed

    private void jButtonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRandomActionPerformed
        // TODO add your handling code here:
        formula=formula+"Random";
        OutputDisplay();
    }//GEN-LAST:event_jButtonRandomActionPerformed

    private void jButtonAdvanceCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdvanceCalculatorActionPerformed
        // TODO add your handling code here:
        //advance calculator window size and reszing function is disabled

        this.setResizable(false);
        this.setSize(816, 560);

    }//GEN-LAST:event_jButtonAdvanceCalculatorActionPerformed

    private void jButtonLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogActionPerformed
        // TODO add your handling code here:
        formula=formula+"log";
        OutputDisplay();
    }//GEN-LAST:event_jButtonLogActionPerformed

    private void jButtonSimpleCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpleCalculatorActionPerformed
        // TODO add your handling code here:
        //main window or simple calculator size and reszing function is disabled
        this.setResizable(false);
        this.setSize(362, 556);
    }//GEN-LAST:event_jButtonSimpleCalculatorActionPerformed

    private void jButtonPower3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPower3ActionPerformed
        // TODO add your handling code here:
        formula=formula+"^3";
        OutputDisplay();
    }//GEN-LAST:event_jButtonPower3ActionPerformed

    private void jButtonPower2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPower2ActionPerformed
        // TODO add your handling code here:
        formula=formula+"^2";
        OutputDisplay();
    }//GEN-LAST:event_jButtonPower2ActionPerformed

    private void jButtonPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPowerActionPerformed
        // TODO add your handling code here:
        formula=formula+"^";
        OutputDisplay();
    }//GEN-LAST:event_jButtonPowerActionPerformed

    private void jButtonUnitConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnitConverterActionPerformed
        // TODO add your handling code here:
                  new UnitConverter().setVisible(true);
    }//GEN-LAST:event_jButtonUnitConverterActionPerformed

    private void jButtonIntegrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntegrationActionPerformed
        // TODO add your handling code here:
         
        new InteDiff().initialize();
//        this.setVisible(false);
        
    }//GEN-LAST:event_jButtonIntegrationActionPerformed

    private void jButtonXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXActionPerformed
        // TODO add your handling code here:
        if(jToggleStore.isSelected()) {
					if(formula.length()>0) {
						calculations.set(format_problem());
						String tmp_ans= calculations.evaluate();
						jTexOutputDisplay.setText(tmp_ans);
						mem_x= Double.parseDouble(tmp_ans);
					}
					else {
						mem_x= Double.parseDouble(answer);
					}
				}
				else {
					formula= formula+'X';
				}
				jToggleStore.setSelected(false);
				OutputDisplay();
    }//GEN-LAST:event_jButtonXActionPerformed

    private void jButtonAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAllClearActionPerformed
        // TODO add your handling code here:
        formula= "";
	jTexOutputDisplay.setText("");
	current_h_pos=0;
	OutputDisplay();
    }//GEN-LAST:event_jButtonAllClearActionPerformed

    private void jButtonNull4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNull4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNull4ActionPerformed

    private void jButtonUCDLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUCDLogoActionPerformed
        // TODO add your handling code here:
        try {
            Desktop.getDesktop().open(new java.io.File("src/WiCaDi.pdf"));
        } catch (IOException e) {
            System.out.println("File not Found. Please reffer the manul in the src folder");
        }
    }//GEN-LAST:event_jButtonUCDLogoActionPerformed

    private void jButtonLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLnActionPerformed
        // TODO add your handling code here:
        formula=formula+"ln";
        OutputDisplay();
    }//GEN-LAST:event_jButtonLnActionPerformed

    private void jButtonYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYActionPerformed
        // TODO add your handling code here:
        if(jToggleStore.isSelected()) {
					if(formula.length()>0) {
						calculations.set(format_problem());
						String tmp_ans= calculations.evaluate();
						jTexOutputDisplay.setText(tmp_ans);
						mem_y= Double.parseDouble(tmp_ans);
					}
					else {
						mem_y= Double.parseDouble(answer);
					}
				}
				else {
					formula= formula+'Y';
				}
				jToggleStore.setSelected(false);
				OutputDisplay();
    }//GEN-LAST:event_jButtonYActionPerformed

    private void jButtonZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZActionPerformed
        // TODO add your handling code here:
        if(jToggleStore.isSelected()) {
					if(formula.length()>0) {
						calculations.set(format_problem());
						String tmp_ans= calculations.evaluate();
						jTexOutputDisplay.setText(tmp_ans);
						mem_z= Double.parseDouble(tmp_ans);
					}
					else {
						mem_z= Double.parseDouble(answer);
					}
				}
				else {
					formula= formula+'Z';
				}
				jToggleStore.setSelected(false);
				OutputDisplay();
    }//GEN-LAST:event_jButtonZActionPerformed

    private void jButtonGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGraphActionPerformed
        // TODO add your handling code here:
        G_Calc GraphC = new G_Calc();
        try {
            GraphC.run();
        } catch (Exception e) {
           
        }
    }//GEN-LAST:event_jButtonGraphActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        formula=formula+"0";
        OutputDisplay();
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed
        // TODO add your handling code here:
        formula=formula+".";
        OutputDisplay();
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        formula=formula+"1";
        OutputDisplay();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        formula=formula+"2";
        OutputDisplay();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        formula=formula+"3";
        OutputDisplay();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        formula=formula+"6";
        OutputDisplay();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        formula=formula+"5";
        OutputDisplay();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        formula=formula+"4";
        OutputDisplay();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        formula=formula+"7";
        OutputDisplay();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        formula=formula+"8";
        OutputDisplay();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        formula=formula+"9";
        OutputDisplay();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
//        formula=formula+"";
//        OutputDisplay();

        try {
                formula= formula.substring(0, (formula.length()-current_cur_pos-1)) + formula.substring(formula.length()-current_cur_pos);
            }
	catch(Exception exc) {
					
                                }
	OutputDisplay();



    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualActionPerformed
        // TODO add your handling code here:
        OutputDisplay();
	EquationHistory(formula);
	calculations.set(format_problem());
	answer= calculations.evaluate();
	jTexOutputDisplay.setText(answer);
        formula= "";
	current_h_pos= 0;
    }//GEN-LAST:event_jButtonEqualActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        formula=formula+"+";
        OutputDisplay();
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplyActionPerformed
        // TODO add your handling code here:
        formula=formula+"*";
        OutputDisplay();
    }//GEN-LAST:event_jButtonMultiplyActionPerformed

    private void jButtonDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivideActionPerformed
        // TODO add your handling code here:
        formula=formula+"/";
        OutputDisplay();
    }//GEN-LAST:event_jButtonDivideActionPerformed

    private void jButtonSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSinActionPerformed
        // TODO add your handling code here:
        formula=formula+"Sin";
        OutputDisplay();
    }//GEN-LAST:event_jButtonSinActionPerformed

    private void jButtonCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCosActionPerformed
        // TODO add your handling code here:
        formula=formula+"Cos";
        OutputDisplay();
    }//GEN-LAST:event_jButtonCosActionPerformed

    private void jButtonSquareRootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSquareRootActionPerformed
        // TODO add your handling code here:
        formula=formula+"√";
        OutputDisplay();
    }//GEN-LAST:event_jButtonSquareRootActionPerformed

    private void jButtonTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTanActionPerformed
        // TODO add your handling code here:
        formula=formula+"Tan";
        OutputDisplay();
    }//GEN-LAST:event_jButtonTanActionPerformed

    private void jTexOutputDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexOutputDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexOutputDisplayActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        formula=formula+"-";
        OutputDisplay();
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonNull8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNull8ActionPerformed
        // TODO add your handling code here:
        calculations.set(format_problem());
	String tmp_ans= calculations.evaluate();
	jTexOutputDisplay.setText(tmp_ans);
	mem= mem+ Double.parseDouble(tmp_ans);
        
    }//GEN-LAST:event_jButtonNull8ActionPerformed

    private void jButtonNull9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNull9ActionPerformed
        // TODO add your handling code here:
        calculations.set(format_problem());
	String tmp_ans= calculations.evaluate();
        jTexOutputDisplay.setText(tmp_ans);
	mem= mem- Double.parseDouble(tmp_ans);
    }//GEN-LAST:event_jButtonNull9ActionPerformed

    private void jButtonNull10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNull10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNull10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Calculator().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
                
            }
        });
    }
    
    
    
    
    // Starts Here
    
    
    
    
    //Ends Here

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAdvanceCalculator;
    private javax.swing.JButton jButtonAllClear;
    private javax.swing.JButton jButtonCos;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDivide;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEqual;
    private javax.swing.JButton jButtonGraph;
    private javax.swing.JButton jButtonIntegration;
    private javax.swing.JButton jButtonLeftBracket;
    private javax.swing.JButton jButtonLn;
    private javax.swing.JButton jButtonLog;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMultiply;
    private javax.swing.JButton jButtonNull10;
    private javax.swing.JButton jButtonNull3;
    private javax.swing.JButton jButtonNull4;
    private javax.swing.JButton jButtonNull8;
    private javax.swing.JButton jButtonNull9;
    private javax.swing.JButton jButtonPi;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPower;
    private javax.swing.JButton jButtonPower2;
    private javax.swing.JButton jButtonPower3;
    private javax.swing.JButton jButtonRandom;
    private javax.swing.JButton jButtonRightBracket;
    private javax.swing.JButton jButtonSimpleCalculator;
    private javax.swing.JButton jButtonSin;
    private javax.swing.JButton jButtonSquareRoot;
    private javax.swing.JButton jButtonTan;
    private javax.swing.JButton jButtonUCDLogo;
    private javax.swing.JButton jButtonUnitConverter;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTexOutputDisplay;
    private javax.swing.JTextField jTextInputDisplay;
    private javax.swing.JToggleButton jToggleStore;
    // End of variables declaration//GEN-END:variables
}
